[[permission]]
identifier = "allow-attach-mud-connection"
description = "Enables the attach_mud_connection command without any pre-configured scope."
commands.allow = ["attach_mud_connection"]

[[permission]]
identifier = "deny-attach-mud-connection"
description = "Denies the attach_mud_connection command without any pre-configured scope."
commands.deny = ["attach_mud_connection"]
