# Allows the frontend to move the default log folder.

[[permission]]
identifier = "allow-move-default-log-folder"
description = "Enables the move_default_log_folder command without any pre-configured scope."
commands.allow = ["move_default_log_folder"]

[[permission]]
identifier = "deny-move-default-log-folder"
description = "Denies the move_default_log_folder command without any pre-configured scope."
commands.deny = ["move_default_log_folder"]
