[[permission]]
identifier = "allow-spellcheck-add"
description = "Enables the spellcheck_add command without any pre-configured scope."
commands.allow = ["spellcheck_add"]

[[permission]]
identifier = "deny-spellcheck-add"
description = "Denies the spellcheck_add command without any pre-configured scope."
commands.deny = ["spellcheck_add"]
