[[permission]]
identifier = "allow-window-open-plain-native-window"
description = "Enables the window_open_plain_native_window command without any pre-configured scope."
commands.allow = ["window_open_plain_native_window"]

[[permission]]
identifier = "deny-window-open-plain-native-window"
description = "Denies the window_open_plain_native_window command without any pre-configured scope."
commands.deny = ["window_open_plain_native_window"]
