[[permission]]
identifier = "allow-window-request-attention"
description = "Enables the window_request_attention command without any pre-configured scope."
commands.allow = ["window_request_attention"]

[[permission]]
identifier = "deny-window-request-attention"
description = "Denies the window_request_attention command without any pre-configured scope."
commands.deny = ["window_request_attention"]
