[[permission]]
identifier = "allow-window-start-resize-dragging"
description = "Enables the window_start_resize_dragging command without any pre-configured scope."
commands.allow = ["window_start_resize_dragging"]

[[permission]]
identifier = "deny-window-start-resize-dragging"
description = "Denies the window_start_resize_dragging command without any pre-configured scope."
commands.deny = ["window_start_resize_dragging"]
